server:
  port: 80 #服务端口
spring:
  profiles:
    active: dev  #环境设置
  application:
    name: servic-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true #可以发现nacos中的微服务，并自动生成转发路由
      routes: # - 代表数组，routes下面有三个配置项 表示并列
      - id: service-core
        uri: lb://service-core
        predicates:
          - Path=/*/core/**
      - id: service-sms
        uri: lb://service-sms
        predicates:
          - Path=/*/sms/**
      - id: service-oss
        uri: lb://service-oss
        predicates:
           - Path=/*/oss/**