server:
  port: 8120

spring:
  profiles:
    active: dev
  application:
    name: service-sms

  # redis放在spring节点下
  redis:
    host: 192.168.186.128
    port: 6379
    database: 1
    #    password: root
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20   #最大连接数，负值表示没有限制，默认8
        max-wait: -1     #最大阻塞等待时间，负值表示没限制 默认 -1
        max-idle: 8      #最大空闲连接，默认8
        min-idle: 0      #最小空闲连接，默认0

#阿里云短信  id 及以下根据实际自己的来  自定义配置
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: LTAI4G5Svnb2TWBMuKnNT6jy
    key-secret: N7v6R4V3EJ1SGDZlsqtqo8QyVVMmtQ
    template-code: SMS_96695065
    sign-name: 谷粒