server:
  port: 8130

spring:
  profiles:
    active: dev
  application:
    name: service-oss

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LSIDUF45SD5F45SD6FDF
    keySecret: ALFJ57SDF454S5SD638JYD
    bucketName: srb-file-202322